### ISSUE TITLE
Kaggle Demos don't load

### ISSUE THREAD

**Issue by irmaR** [FeatureLabs/autonormalize#11]
Hi,

I tried to view your two Kaggle Demos on github but for some reason they are not loading. I can view and run AutoNormalize + FeatureTools Demo.ipynb one.

Irma

**Comment by kmax12** [comment]
@irmaR can you share the error or what your are seeing when you try to load?

**Comment by irmaR** [comment]
Hi, here it is. 
![Screenshot from 2019-10-17 13-35-32](https://user-images.githubusercontent.com/2535881/67045524-5244e500-f0e3-11e9-8fc3-61e87d6b5f05.png)

Thanks.

**Comment by kmax12** [comment]
github has trouble loading jupyter notebooks. trying copy and pasting the url here: https://nbviewer.jupyter.org
